# Generated by Django 3.2.5 on 2021-07-19 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/')),
                ('image2', models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/')),
                ('image1', models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/')),
                ('image3', models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/')),
                ('image4', models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/')),
                ('image5', models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/')),
                ('title', models.CharField(max_length=100)),
                ('smol_text', models.TextField(default='Информация от мэра города не поступила.', max_length=400)),
                ('text', models.TextField(default='Информация от мэра города не поступила.')),
                ('contact_url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('author', models.CharField(default='ananist', max_length=100)),
                ('mayor', models.CharField(default='ananist', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/image/')),
                ('title', models.CharField(max_length=1000)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pyblished_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.CharField(default='ananist', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Penetration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minecraft_nickname', models.CharField(default='Не указано', max_length=100)),
                ('site_username', models.CharField(default='Не указано', max_length=100)),
                ('donation_username', models.CharField(default='Не указано', max_length=100)),
                ('free_token', models.CharField(default='Не указано', max_length=300)),
                ('donation_image', models.ImageField(blank=True, default='penetration/image/default/default.png', upload_to='penetration/image/')),
                ('description_yourself', models.TextField(default='Не описано.')),
                ('how_you_know', models.TextField(default='Не описано.')),
                ('contact', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/')),
                ('image1', models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/')),
                ('image2', models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/')),
                ('image3', models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/')),
                ('image4', models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/')),
                ('image5', models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/')),
                ('title', models.CharField(max_length=100)),
                ('smol_text', models.TextField(default='Информация от мэра города не поступила.', max_length=400)),
                ('text', models.TextField(default='Информация от мэра города не поступила.')),
                ('contact_url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('author', models.CharField(default='ananist', max_length=100)),
                ('mayor', models.CharField(default='ananist', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='none', max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('userid', models.CharField(default=3, max_length=1000)),
                ('role', models.CharField(default='Игрок', max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unconfirmed_discord', models.CharField(max_length=100)),
                ('user_image', models.ImageField(blank=True, default='users/user_image/default/default.png', upload_to='users/user_image/')),
                ('info', models.TextField(default='Проходивший мимо пользователь сайта,который ничего о себе не написал', max_length=1000)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('Игрок', 'Игрок'), ('Журналист', 'Журналист'), ('Мэр', 'Мэр'), ('Президент', 'Президент'), ('ФБР', 'ФБР'), ('Глава ФБР', 'Глава ФБР')], default='Игрок', max_length=9)),
                ('discord', models.CharField(max_length=100)),
                ('admin', models.BooleanField(default=False)),
                ('registered', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='none', max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('userid', models.CharField(default=3, max_length=1000)),
                ('role', models.CharField(default='Игрок', max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.news')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
