# Generated by Django 3.2.3 on 2021-06-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ('create_date', 'role')},
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.TextField(),
        ),
    ]
