# Generated by Django 3.2.3 on 2021-06-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210617_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ('create_date',)},
        ),
        migrations.RemoveField(
            model_name='users',
            name='image',
        ),
    ]
