# Generated by Django 3.2.3 on 2021-06-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210617_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.TextField(default='Игрок'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, default='users/user_image/default/default.png', upload_to='users/user_image/'),
        ),
    ]
