# Generated by Django 3.2.3 on 2021-06-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210618_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='info',
            field=models.TextField(default='Проходивший мимо пользователь сайта, который ничего о себе не написал'),
        ),
    ]
