# Generated by Django 3.2.3 on 2021-06-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profile_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(default='Проходивший мимо пользователь сайта, который ничего о себе не написал', max_length=1000),
        ),
    ]
