# Generated by Django 3.2.3 on 2021-06-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210618_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='year_in_school',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('r1', 'Игрок'), ('r2', 'Журналист'), ('r3', 'Мэр'), ('r4', 'Президент'), ('r5', 'ФБР')], default='r1', max_length=2),
        ),
    ]
