# Generated by Django 3.2.3 on 2021-06-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210618_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Игрок', 'Игрок'), ('Журналист', 'Журналист'), ('Мэр', 'Мэр'), ('Президент', 'Президент'), ('ФБР', 'ФБР')], default='Игрок', max_length=9),
        ),
    ]
