# Generated by Django 3.2.3 on 2021-06-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_city_mayor'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image1',
            field=models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/'),
        ),
        migrations.AddField(
            model_name='city',
            name='image2',
            field=models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/'),
        ),
        migrations.AddField(
            model_name='city',
            name='image3',
            field=models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/'),
        ),
        migrations.AddField(
            model_name='city',
            name='image4',
            field=models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/'),
        ),
        migrations.AddField(
            model_name='city',
            name='image5',
            field=models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, default='city/image/default/default.png', upload_to='city/image/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='smol_text',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='city',
            name='text',
            field=models.TextField(),
        ),
    ]
