# Generated by Django 3.2.3 on 2021-06-22 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_penetration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='penetration',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
