# Generated by Django 3.2.3 on 2021-06-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_penetration_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penetration',
            name='how_you_know',
            field=models.TextField(default='Не описано.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='registered',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
