# Generated by Django 3.2.3 on 2021-06-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210622_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
