# Generated by Django 3.2.3 on 2021-06-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_role',
            field=models.CharField(default='Игрок', max_length=100),
        ),
    ]
