# Generated by Django 3.2.3 on 2021-06-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20210622_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_role',
            new_name='role',
        ),
    ]
