# Generated by Django 3.2.3 on 2021-06-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_usercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.CharField(default=2, max_length=1000),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='userid',
            field=models.CharField(default=2, max_length=1000),
        ),
    ]
