# Generated by Django 3.2.3 on 2021-06-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210623_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='userid',
        ),
    ]
