# Generated by Django 3.2.3 on 2021-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_rename_user_id_comment_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unconfirmed_discord',
            field=models.CharField(default='Не задан', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userid',
            field=models.CharField(default=3, max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(default='Проходивший мимо пользователь сайта,который ничего о себе не написал', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='userid',
            field=models.CharField(default=3, max_length=1000),
        ),
    ]
