# Generated by Django 3.2.3 on 2021-07-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20210719_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='status',
            field=models.CharField(choices=[('Открыт', 'Открыт'), ('Закрыт', 'Закрыт'), ('Не функционирует', 'Не функционирует')], default='Открыт', max_length=17),
        ),
    ]
