# Generated by Django 3.2.3 on 2021-07-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_city_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_fruit',
            field=models.CharField(default='ананас', max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Игрок', max_length=9),
        ),
    ]
