# Generated by Django 3.2.3 on 2021-07-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20210720_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_fruit',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Игрок', 'Игрок'), ('Журналист', 'Журналист'), ('Мэр', 'Мэр'), ('Президент', 'Президент'), ('ФБР', 'ФБР'), ('Глава ФБР', 'Глава ФБР')], default='Игрок', max_length=9),
        ),
    ]
