# Generated by Django 3.2.3 on 2021-07-22 06:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Игрок', 'Игрок'), ('Журналист', 'Журналист'), ('Мэр', 'Мэр'), ('Представитель города', 'Представитель города'), ('ФБР', 'ФБР'), ('Глава ФБР', 'Глава ФБР')], default='Игрок', max_length=54),
        ),
    ]
